### ISSUE TITLE
Is it possible to create a condition referencing 2 data points in the input JSON?

### ISSUE THREAD

**Issue by Altonymous** [aparande/json-mapping-transform#1]
Input JSON
```
{
  "name": "Trader Joe's",
  "location": "Berkeley, California",
  "weeklyVisitors": 5000,
  "storeId": 1234,
  "employees": [
    { "name": "Jim Shoes" },
    { "name": "Kay Oss" }
  ],
  "inventory": [
    { "itemName": "Apples", "price": 0.5, "unit": "lb" },
    { "itemName": "Oranges", "price": 2, "unit": "lb" },
    { "itemName": "Bag of Carrots", "price": 1.5, "unit": "count" }
  ]
}
```

Conditions Example
```
---
conditions:
  apple_condition:
    class: AppleCondition
  
objects:
- name: apple
  path: 
  - "/storeId"
  - "/inventory"
  conditions:
  - name: apple_condition
```

```
module Conditions
  class AppleCondition < BaseCondition
    def apply(value1, value2)
      puts value1
      puts value2
      ...
    end
  end
end

output = JsonMapping.new(path).map(store_fixture)
```
